### ISSUE TITLE
yarn throws errors when trying to install due to broken fontawesome registry

### ISSUE THREAD

**Issue by slugalisk** [GuacLive/guac-web#3]
yarn throws an error when installing because the fontawesome registry is broken.

```
guac-web$ yarn install
yarn install v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://npm.fontawesome.com/@fortawesome/fontawesome-common-types/-/fontawesome-common-types-0.2.17.tgz: Request failed \"401 Unauthorized\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/slugalisk/projects/memes/guac-web/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

most of these packages are available from yarnpkg but not the fontawesome-pro package...

```
guac-web$ yarn install
yarn install v1.15.2
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@fortawesome/fontawesome-pro/-/fontawesome-pro-5.8.1.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/slugalisk/projects/memes/guac-web/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

this isn't used anywhere currently so it seems safe to remove it.

i didn't see any instructions for contributing but this pr fixes the issues: https://github.com/GuacLive/guac-web/pull/2

**Comment by datagutt** [comment]
Hi,
Thanks for your interest. That registry is throwing a 401 because it expects you to be "logged in" to it for access to Pro (paid) icons.
Using pro icons in an open source project obviously makes no sense, so i am going to go ahead and merge #2 .

Currently i don't have much of usage instructions, let alone contributing instructions. This is something i will try to fix in the upcoming days.
The guac-web and guac-chat also relies on guac-api, which is currently a private repo that i haven't gotten around to putting public yet. Will try to get that done in the upcoming days as well.
